### ISSUE TITLE
Images with distorted aspect ratio

### ISSUE THREAD

**Issue by biinniit** [reuben54/32smiles#3]
The images on your [Teeth Whitening](/reuben54/32smiles/blob/main/teeth%20whitening.html) page still have distorted aspect ratio.

Remember:
```css
img {
  object-fit: cover;
}
```
